{{ ... }}
    - name: Install Lambda dependencies
      run: |
        cd files/deployable
        npm install
{{ ... }}
    - name: Install dependencies
      run: |
        cd files/deployable
        npm install
